name: nlp-final
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - tqdm
  - matplotlib
  - pytorch>=2.0
  - pip:
      - datasets>=2.0
      - transformers>=4.35
      - evaluate
      - huggingface-hub
      - sentencepiece
      - tokenizers
      - safetensors
      - scikit-learn